### ISSUE TITLE
No module named 'metrics'

### ISSUE THREAD

**Issue by jiangpinghuang** [mingdachen/syntactic-template-generation#1]
Hi, there is a ModuleNotFoundError as following when I run "run-vgvae.sh". Where is the metrics?

Traceback (most recent call last):
  File "train.py", line 1, in <module>
    import train_helper
  File "/home/hjp/Downloads/tmp/tmp/stg/train_helper.py", line 16, in <module>
    from metrics import Meteor
ModuleNotFoundError: No module named 'metrics'

**Comment by mingdachen** [comment]
Hi, thanks for reporting. "Meteor" is in the eval_utils. Will push a fix later.
