### ISSUE TITLE
FileNotFoundError: latest.ckpt

### ISSUE THREAD

**Issue by jiangpinghuang** [mingdachen/syntactic-template-generation#2]
**Hi, when I run the command "sh run-vgvae.sh", the terminal shows the following FileNotFoundError:**

log exists: vgvae-exp/desize100edim100ensize100gmkl0.001vmkl0.0001ymlplayer2ysize50zmlplayer2zsize50
Namespace(auto_disconnect=True, batch_size=30, debug=False, decoder_type='lstm_z2y', desize=100, dev_inp_path='dev_input.txt', dev_ref_path='dev_ref.txt', dp=0.0, edim=100, embed_file='glove.6B.100d.txt', embed_type='glove', ensize=100, eps=0.0001, eval_every=5000, gclip=None, gmkl=0.001, l2=0.0, lr=0.001, lratio=1.0, mhsize=100, mlplayer=3, n_epoch=20, nclass=2, ncode=8, opt='adam', plratio=1.0, pratio=1.0, pre_train_emb=True, print_every=500, ps=0.0, resume=True, save_dir=None, save_prefix='vgvae-exp', summarize=True, tag_vocab_file='word2tag.pkl', test_inp_path='test_input.txt', test_ref_path='test_ref.txt', train_path='train.txt', train_tag_path='train.tag', vmkl=0.0001, vocab_file='vocab', vocab_size=50000, wr=0.0, yencoder_type='word_avg', ymlplayer=2, ysize=50, zencoder_type='bilstm', zmlplayer=2, zsize=50)
log saving to vgvae-exp/desize100edim100ensize100gmkl0.001vmkl0.0001ymlplayer2ysize50zmlplayer2zsize50/log
Traceback (most recent call last):
  File "train.py", line 177, in <module>
    run(e)
  File "train.py", line 34, in run
    model.load(name="latest")
  File "/home/hjp/Downloads/tmp/tmp/stg/models.py", line 108, in load
    map_location=lambda storage,
  File "/home/hjp/Workspace/Tempshop/Python/Conda/envs/Env36Py100/lib/python3.6/site-packages/torch/serialization.py", line 365, in load
    f = open(f, 'rb')
**FileNotFoundError: [Errno 2] No such file or directory: 'vgvae-exp/desize100edim100ensize100gmkl0.001vmkl0.0001ymlplayer2ysize50zmlplayer2zsize50/latest.ckpt'**
()
best dev bleu: 0.0000, test bleu: 0.0000

**It seems that there is no latest.ckpt in the directory: vgvae-exp/desize100edim100ensize100gmkl0.001vmkl0.0001ymlplayer2ysize50zmlplayer2zsize50/**

**Comment by mingdachen** [comment]
Hi, thanks for reporting. Can you manually delete this directory? I believe it is caused by the fact that your last experiment failed unexpectedly -- the program will automatically search for the latest checkpoint and resume from it. If the program failed before generating a checkpoint, it will lead to the failure you are seeing.

**Comment by hjpwhu** [comment]
Thanks for your reply. It works. However, it produces new error as following:

Namespace(auto_disconnect=True, batch_size=30, debug=False, decoder_type='lstm_z2y', desize=100, dev_inp_path='dev_input.txt', dev_ref_path='dev_ref.txt', dp=0.0, edim=100, embed_file='glove.6B.100d.txt', embed_type='glove', ensize=100, eps=0.0001, eval_every=5000, gclip=None, gmkl=0.001, l2=0.0, lr=0.001, lratio=1.0, mhsize=100, mlplayer=3, n_epoch=20, nclass=2, ncode=8, opt='adam', plratio=1.0, pratio=1.0, pre_train_emb=True, print_every=500, ps=0.0, resume=False, save_dir=None, save_prefix='vgvae-exp', summarize=True, tag_vocab_file='word2tag.pkl', test_inp_path='test_input.txt', test_ref_path='test_ref.txt', train_path='train.txt', train_tag_path='train.tag', vmkl=0.0001, vocab_file='vocab', vocab_size=50000, wr=0.0, yencoder_type='word_avg', ymlplayer=2, ysize=50, zencoder_type='bilstm', zmlplayer=2, zsize=50)
log saving to vgvae-exp/desize100edim100ensize100gmkl0.001vmkl0.0001ymlplayer2ysize50zmlplayer2zsize50/log
Traceback (most recent call last):
  File "train.py", line 177, in <module>
    run(e)
  File "train.py", line 102, in run
    dev_stats, dev_bleu = dev_eval.evaluate("gen_dev")
  File "/home/hjp/Downloads/tmp/tmp/stg/train_helper.py", line 261, in evaluate
    stats['meteor'] += meteor._score(hyp, [ref])
  File "/home/hjp/Downloads/tmp/tmp/stg/eval_utils.py", line 73, in _score
    self.meteor_p.stdin.flush()
**BrokenPipeError: [Errno 32] Broken pipe**
()
best dev bleu: 0.0000, test bleu: 0.0000

Thanks for you help.
